image: registry.gitlab.com/cyberark/cloudfoundry-conjur-buildpack/gitlab-dind:latest
# 
# This container image is used for running CI stages.
# It contains all the common utilities; docker, git, docker-compose, openssl etc.
# This image coupled with the docker:stable-dind service makes it possible to 
# leverage the Gitlab runner's Docker daemon during CI stages.
# 
# This container image can be built by running the following:
# 
# echo "
# FROM docker:stable-git
# RUN apk add --no-cache bash openssl py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
# RUN pip install docker-compose
# " | docker build -t registry.gitlab.com/cyberark/cloudfoundry-conjur-buildpack/gitlab-dind:latest -
#


stages:
  - test

test:
  stage: test
  services:
  - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
  artifacts:
    untracked: true
    reports:
      junit: ci/features/reports/*.xml
    when: always
  script:
    - ./package.sh
    - ./test.sh
  only:
    - branches

before_script:
- apk add --no-cache bash
