image: docker:stable-git

stages:
  - test

test:
  stage: test
  services:
  - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
  artifacts:
    untracked: true
    reports:
      junit: ci/features/reports/*.xml
    when: always
  script:
    - ./package.sh
    - ./test.sh
  only:
    - branches

before_script:
- apk add --no-cache bash
